# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tamano', models.IntegerField(default=0)),
                ('lugar_de_plantacion', models.CharField(choices=[(1, 'Interior'), (2, 'Exterior')], max_length=200)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.clasificacion')),
            ],
        ),
    ]
