# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacion',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='especie',
            name='lugar_de_plantacion',
            field=models.IntegerField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior'), ('Ambas', 'Ambas')]),
        ),
    ]
