# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 19:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_auto_20170217_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='planta',
            fields=[
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_plantacion', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='Distancia_entre_siembras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='especie',
            name='altura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='especie',
            name='color',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AddField(
            model_name='especie',
            name='comienzo_siembra',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='especie',
            name='descripcion',
            field=models.CharField(default='NONE', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='descripcion_de_flor',
            field=models.CharField(default='NONE', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='descripcion_de_fruto',
            field=models.CharField(default='NONE', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='familia',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AddField(
            model_name='especie',
            name='miembro_cosechable',
            field=models.CharField(choices=[(1, 'Hoja'), (2, 'Raiz'), (3, 'Flor'), (4, 'Bulbo')], default='No especificada.', max_length=200),
        ),
        migrations.AddField(
            model_name='especie',
            name='nombre_cientifico',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AddField(
            model_name='especie',
            name='ph',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='especie',
            name='requerimientos_de_riego',
            field=models.CharField(default='NONE', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='requerimientos_de_suelo',
            field=models.CharField(default='NONE', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='temperatura_de_crecimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='especie',
            name='temperatura_de_germinacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='especie',
            name='termino_siembra',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='descripcion',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='nombre',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='lugar_de_plantacion',
            field=models.CharField(choices=[(1, 'Interior'), (2, 'Exterior'), (3, 'Ambas')], default='No especificada.', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(default='NONE', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.especie'),
        ),
        migrations.AddField(
            model_name='planta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
