# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20170516_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especie',
            old_name='Distancia_entre_siembras',
            new_name='distancia_entre_siembras',
        ),
        migrations.AlterField(
            model_name='especie',
            name='descripcion',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='descripcion_de_flor',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='descripcion_de_fruto',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='requerimientos_de_riego',
            field=models.CharField(default='NONE', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='requerimientos_de_suelo',
            field=models.CharField(default='NONE', max_length=200),
        ),
    ]
